# AUTH (public)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# PRODUCT (secured)
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthFilter

# ORDER (secured)
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://order-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthFilter

# TEST PROTECTED (IMPORTANT)
spring.cloud.gateway.routes[1].id=test-route
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/test/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthFilter
